### PR TITLE
Update to version 31.22

### PR DESCRIPTION
**Pull request by fepitre**
QubesOS/qubes-issues#5529

### CODE REVIEW

**Comment by marmarek** [comment]
The new partitioning code creates "qubesos_dom0" LVM volume group now, instead of "qubes_dom0". This isn't a big issue, but may confuse some users and also make some documentation obsolete. If easy, please change back to "qubes_dom0".

**Comment by fepitre** [comment]
From what I remembered, I thought that would be hardcoded in the partitionning scheme but it seems to be a general schema. I'll check how to fix that.

**Comment by marmarek** [comment]
Another issue (not sure if here or in lorax-templates) is the installer startup presents itself as "Fedora 31 ..." (in installer boot messages). Probably qubes-release package is not installed there.

**Comment by marmarek** [comment]
And another one - after installation, the disk password prompt is in text mode, not the nice graphical one. Generally plymouth seems to be broken after installation.

**Comment by fepitre** [comment]
> And another one - after installation, the disk password prompt is in text mode, not the nice graphical one. Generally plymouth seems to be broken after installation.

So from what discussed, this is not an issue but missing plymouth option with respect to your setup? configuration.

**Comment by fepitre** [comment]
> l

And this one is solved by https://github.com/QubesOS/qubes-lorax-templates/pull/5.

**Comment by fepitre** [comment]
> Another issue (not sure if here or in lorax-templates) is the installer startup presents itself as "Fedora 31 ..." (in installer boot messages). Probably qubes-release package is not installed there.

And this one is solved by QubesOS/qubes-lorax-templates#5.

**Pull request merged**
