### PR TITLE
Workaround issue when installing with iso-scan

### LINKED ISSUE #6792: QubesOS 4.1 installer over Heads ISO boot: blivet doesn't find mount attribute on already mounted loopback device for install when installing packages
### Qubes OS version

QubesOS 4.1 ISO (Qubes-R4.1.0-beta1pre1-x86_64) 

### Affected component(s) or functionality

QubesOS Installer over Heads (USB boot of verified detached signed ISO)

-----
### Brief summary

@marmarek @fepitre : The following happens in blivet after default partitioning of the system, right before installing packages:

```
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]: DEBUG:blivet:              DeviceTree.get_device_by_name: name: /run/initramfs/isoscan/Qubes-R4.1.0-beta1pre1-x86_64.iso ; incomplete: True ; hidden: True ;
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]: DEBUG:blivet:              DeviceTree.get_device_by_name returned existing 0 B file /run/initramfs/isoscan/Qubes-R4.1.0-beta1pre1-x86_64.iso (44)
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]: WARNING:dasbus.server.handler:The call org.fedoraproject.Anaconda.Modules.Storage.DeviceTree.Handler.MountDevice has failed with an exception:
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]: Traceback (most recent call last):
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:   File "/usr/lib/python3.8/site-packages/dasbus/server/handler.py", line 409, in _method_callback
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:     result = self._handle_call(
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:   File "/usr/lib/python3.8/site-packages/dasbus/server/handler.py", line 234, in _handle_call
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:     return handler(*parameters)
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:   File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/devicetree/handler_interface.py", line 56, in MountDevice
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:     self.implementation.mount_device(device_name, mount_point)
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:   File "/usr/lib64/python3.8/site-packages/pyanaconda/modules/storage/devicetree/handler.py", line 94, in mount_device
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]:     device.format.mount(mountpoint=mount_point)
Jul 24 14:56:01 localhost org.fedoraproject.Anaconda.Modules.Storage[1649]: AttributeError: 'DeviceFormat' object has no attribute 'mount'
Jul 24 14:56:01 localhost anaconda[1577]: anaconda: threading: Thread Failed: AnaInstallThread (136346816538368)
Jul 24 14:56:01 localhost anaconda[1577]: anaconda: exception: running handleException
Jul 24 14:56:01 localhost anaconda[1577]: anaconda: exception: Traceback (most recent call last):
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/threading.py", line 280, in run
                                              threading.Thread.run(self)
                                          
                                            File "/usr/lib64/python3.8/threading.py", line 870, in run
                                              self._target(*self._args, **self._kwargs)
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation.py", line 382, in run_installation
                                              queue.start()
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
                                              item.start()
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
                                              item.start()
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 311, in start
                                              item.start()
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 490, in start
                                              self.run_task()
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/installation_tasks.py", line 456, in run_task
                                              self._task(*self._task_args, **self._task_kwargs)
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/payload/dnfpayload.py", line 1041, in install
                                              self._setup_media(self.install_device)
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/payload/__init__.py", line 744, in _setup_media
                                              payload_utils.mount_device(device, INSTALL_TREE)
                                          
                                            File "/usr/lib64/python3.8/site-packages/pyanaconda/payload/utils.py", line 74, in mount_device
                                              device_tree.MountDevice(device_name, mount_point)
                                          
                                            File "/usr/lib/python3.8/site-packages/dasbus/client/handler.py", line 442, in _call_method
                                              return self._get_method_reply(
                                          
                                            File "/usr/lib/python3.8/site-packages/dasbus/client/handler.py", line 474, in _get_method_reply
                                              return self._handle_method_error(error)
                                          
                                            File "/usr/lib/python3.8/site-packages/dasbus/client/handler.py", line 496, in _handle_method_error
                                              raise exception from None
                                          
                                          dasbus.error.DBusError: 'DeviceFormat' object has no attribute 'mount'
Jul 24 14:56:01 localhost anaconda[1577]: anaconda: exception: Gtk running, queuing exception handler to the main loop
Jul 24 14:56:01 localhost anaconda[1577]: anaconda: threading: Thread Done: AnaInstallThread (136346816538368)
Jul 24 14:56:04 localhost systemd[1]: anaconda-shell@hvc1.service: Succeeded.
```
Full `journalctl > file` output [here](https://upload.disroot.org/r/R2UDy8RK#R+6YNg3gpwCVAyU1BXlJ+oQADMGxuu+kd9EWpwEM7GE=)
Search for `AttributeError` in the whole dumped log.

### How reproducible

Each install attempt fails at the same point above. Also tested https://qubes.notset.fr/iso/Qubes-20210717-x86_64.iso

### Steps to reproduce

1. Have x230-hotp-maximized Heads [build](https://1189-103208611-gh.circle-artifacts.com/0/build/x230-hotp-maximized/heads-x230-hotp-maximized-v0.2.0-1043-g44be90f.rom) flashed
2. Boot from ISO with a self detached signed iso on USB device (gpg --detach-sign QubesOS.iso, then boot from it)
3. Do normal install, see above error

### Expected behavior

I am not sure why blivet checks again for mountable property of the loop device. Expected behavior would be to continue installation of packages since the ISO is properly mounted already, partitioning has happened and software packages were discovered and are ready to install.

QubesOS 4.0 installers don't show this behavior.

### Actual behavior

Installation fails just before package installation with above error.

### Solutions you've tried

Heads permits to boot from USB a dd'ed copy of the ISO. This works, but is untrusted (unverified).
But the goal here would be to have f[epitre-bot key added into Heads distribution signing keys to validate detached signed ISO images](https://github.com/osresearch/heads/issues/1010#issuecomment-885894290).

### Additional context

-----

### PR DESCRIPTION
**Pull request by fepitre**
Closes: QubesOS/qubes-issues#6792

### CODE REVIEW

**Comment by jkonecny12** [comment]
Hi, could you please port this patch to [Anaconda upstream](https://github.com/rhinstaller/anaconda/)?

If this issue is now in Anaconda it would be great to have at least the work-around with a FIXME comment rather than broken code.

**Comment by marmarek** [comment]
This is actually interesting - we were able to reproduce it on plain F32 anaconda (which this repo is based on), but not on plain F34 install. But also, haven't found specific fix in the git history.

**Comment by fepitre** [comment]
@marmarek @jkonecny12 I can add more details: The original issue can be reproduced on plain Fedora 32 (tested with Server edition DVD ISO) when booting with a GRUB entry:

```
menuentry 'Fedora 32 Server Installation' {
        set isofile='(hd0,msdos1)/Fedora-Server-dvd-x86_64-32-1.6.iso'
        loopback loop $isofile
        linux (loop)/isolinux/vmlinuz inst.stage2=hd:LABEL=Fedora-S-dvd-x86_64-32 findiso=/dev/vda1/Fedora-Server-dvd-x86_64-32-1.6.iso iso-scan/filename=/Fedora-Server-dvd-x86_64-32-1.6.iso
        initrd (loop)/isolinux/initrd.img
}
```
in the setup described in https://github.com/QubesOS/qubes-issues/issues/6792#issuecomment-888602809. So in Fedora 32, it allows to use the "Local media" mounted and found with iso-scan where as for Fedora 34, the Local media is simply not found/ignored and we only have "Closest mirror" choice or search for available ISO files. I think somehow the AttributeError is not raised (by blivet?) and it makes ignoring "Local media".

**Comment by marmarek** [comment]
Oh, it's this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1830553

**Comment by fepitre** [comment]
> Oh, it's this bug: https://bugzilla.redhat.com/show_bug.cgi?id=1830553

Yes this is exactly the observed behavior and notably what happens for Fedora 34 as described in https://bugzilla.redhat.com/show_bug.cgi?id=1830553#c15. I think we can merge effort on that.

**Comment by tlaurion** [comment]
@fepitre : this workaround is included in latest ISOs? (Should fix error in fedora-32 QubesOS based ISO, while not upstream Fedora-34 bug if I understand correctly)?

**Comment by fepitre** [comment]
Superseded by https://github.com/QubesOS/qubes-anaconda/commit/b0ff9181930008b2af452872e1f0a44b9b57718c.

**Pull request closed without merging**
