### PR TITLE
rescue mode can mount Linux partition again

### PR DESCRIPTION
**Pull request by ghost**
Fixes "You don't have any Linux partitions." in the rescue mode.

It took me an hour to figure why did the rescue mode was not able to find
a Linux partition.

If we do not want to mount pre-existing partition nor detect the OS in
the installer, then we should only do that in the installer.

Then, it would be much more useful if the function isn't just getting
chopped off like it was but instead a message explaining why it was
chopped off added. Can save hours for people trying to figure why their
rescue mode isn't finding any Linux partition.

----

Related issue https://github.com/QubesOS/qubes-issues/issues/2835

### CODE REVIEW

**Comment by ghost** [comment]
Hum, I've just skimmed through the issue and can see that this patch prevents against the data loss situations. Probably it's better not to merge this, but rather come with a better fix?

**Comment by ghost** [comment]
Though, the potential "data loss" issue seem to be was fixed here https://github.com/storaged-project/blivet/pull/526/files#diff-cd99c6e4dd15e4148bb0f4d1a214f303R119 ?

**Comment by marmarek** [comment]
It not only do fsck (that's another place and indeed is better now), but also *mounts* every single partition it finds on the disk, and analyze various files found there (/etc/os-release, /etc/fstab etc). Something that can easily end up badly. Imagine you're reinstalling your system over previous compromised one - the amount of parsing of pre-existing disk content here makes it quite likely that it would be possible to plant files that would re-compromise qubes installer...

**Comment by ghost** [comment]
I see the point.
We should still make it working in the rescue mode though.

**Comment by marmarek** [comment]
>  We should still make it working in the rescue mode though.

Yes.

**Comment by ghost** [comment]
> > We should still make it working in the rescue mode though.
> 
> Yes.

I will open a separate issue so not to forget.

Upd: https://github.com/QubesOS/qubes-issues/issues/5609

**Pull request closed without merging**
